---
title: "Casos de dengue"
author: "Pamela Pairo"
date: "2/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pdftools)
library(tidyverse)

pdf1 <- pdf_text ("IF-2021-05150554-APN-DNEEIE#MS.pdf")

pdf1

write (pdf1, "2016.csv")

base_2016 <- read_csv ("2016.csv")

nueva_base <- base_2016 %>% 
  separate(`PROVINCIA  DEPARTAMENTO    CASOS`, into = c("Provincia", "Departamento", "Casos", "V1", "V2"))

buenos<- nueva_base %>% 
  select(Provincia) %>% 
  filter (Provincia %in% c("BUENOS", "SGO", "CAPITAL") )



base2 <- anti_join(nueva_base, buenos) %>% 
  mutate(Provincia = case_when(
    str_detect(Provincia, regex("AIRES", ignore_case = TRUE)) ~ "Buenos Aires",
    str_detect(Provincia, "FEDERAL") ~ "Capital Federal",
    str_detect(Provincia, "ENTRE") ~ "Entre Rios",
    str_detect(Provincia, "SANTA") ~ "Santa Fe",
    str_detect(Provincia, "ESTERO") ~ "Santiago del Estero",
    TRUE ~ as.character(Provincia)
  )) 

write_csv (base2, "2016_nuevo.csv")

```


```{r}
library(rgeoboundaries)
argentina_boundary <- geoboundaries("Argentina", "adm2")

argentina_boundary$shapeID


ggplot(data = argentina_boundary) +
  geom_sf()

```


```{r}
pdf2 <- pdf_text ("IF-2021-05151024-APN-DNEEIE#MS.pdf")

write (pdf2, "2017.csv")

base_2017 <- read_csv ("2017.csv",locale = locale(encoding = "ISO-8859-1"))

nueva_base_2017 <- base_2017 %>% 
  separate(`PROVINCIA DEPARTAMENTO CASOS`, into = c("Provincia", "Departamento", "Casos", "V1", "V2"))

buenos_2017<- nueva_base_2017 %>% 
  select(Provincia) %>% 
  filter (Provincia %in% c("BUENOS", "CAPITAL") )



base2_2017 <- anti_join(nueva_base_2017, buenos_2017) %>% 
  mutate(Provincia = case_when(
    str_detect(Provincia, regex("AIRES", ignore_case = TRUE)) ~ "Buenos Aires",
    str_detect(Provincia, "FEDERAL") ~ "Capital Federal",
    str_detect(Provincia, "ENTRE") ~ "Entre Ríos",
    str_detect(Provincia, "SANTA") ~ "Santa Fé",
    TRUE ~ as.character(Provincia)
  )) 

write_excel_csv (base2_2017, "2017_nuevo.csv")
```

```{r}

pdf3 <- pdf_text ("IF-2021-05151396-APN-DNEEIE#MS.pdf")

write (pdf3, "2018.csv")

base_2018 <- read_csv ("2018.csv",locale = locale(encoding = "ISO-8859-1"))

nueva_base_2018 <- base_2018 %>% 
  separate(`PROVINCIA   DEPARTAMENTO     CASOS`, into = c("Provincia", "Departamento", "Casos", "v1", "v2"), sep= "[[:space:]]+")

base2_2018 <- nueva_base_2018 %>% 
  mutate(Provincia = case_when(
    str_detect(Provincia, regex("Buenos", ignore_case = TRUE)) ~ "Buenos Aires",
    str_detect(Provincia, "CABA") ~ "Capital Federal",
    str_detect(Provincia, "Entre") ~ "Entre Ríos",
    str_detect(Provincia, "Santa") ~ "Santa Fé",
    str_detect(Provincia, "Santiago") ~ "Santiago del Estero",
    TRUE ~ as.character(Provincia)
  )) 

write_excel_csv (base2_2018, "2018_nuevo.csv")

base2_2018<- gsub("(?<=\\b.)(.*?)\\b", "\\L\\1", base2_2018, perl=TRUE)

base2_2018 <- as.data.frame.table(base2_2018)

```

```{r}

pdf4 <- pdf_text ("IF-2021-05151812-APN-DNEEIE#MS.pdf")

write (pdf4, "2019.csv")

base_2019 <- read_csv ("2019.csv", locale = locale(encoding = "ISO-8859-1"))

nueva_base_2019 <- base_2019 %>% 
  separate(`PROVINCIA DEPARTAMENTO CASOS`, into = c("Provincia", "Departamento", "Casos", "v1", "v2"),sep= "[[:space:]]+")

buenos_2019<- nueva_base_2019 %>% 
  select(Provincia) %>% 
  filter (Provincia %in% c("Buenos") )

base2_2019 <- anti_join(nueva_base_2019, buenos_2019) %>% 
  mutate(Provincia = case_when(
    str_detect(Provincia, regex("Aires", ignore_case = TRUE)) ~ "Buenos Aires",
    str_detect(Provincia, "CABA") ~ "Capital Federal",
    str_detect(Provincia, "Santa") ~ "Santa Fé",
    TRUE ~ as.character(Provincia)
  )) 

write_csv (base2_2019, "2019_nuevo.csv")

```

```{r}

pdf5 <- pdf_text ("IF-2021-05152084-APN-DNEEIE#MS.pdf")

write (pdf5, "2020.csv")

base_2020 <- read_csv ("2020.csv", locale = locale(encoding = "ISO-8859-1"))

nueva_base_2020 <- base_2020 %>% 
  separate(`PROVINCIA DEPARTAMENTO    CASOS`, into = c("Provincia", "Departamento", "Casos", "v1", "v2"),sep= "[[:space:]]+")

buenos_2020<- nueva_base_2020 %>% 
  select(Provincia) %>% 
  filter (Provincia %in% c("Buenos", "Santiago") )

base2_2020 <- anti_join(nueva_base_2020, buenos_2020) %>% 
  mutate(Provincia = case_when(
    str_detect(Provincia, regex("Aires", ignore_case = TRUE)) ~ "Buenos Aires",
    str_detect(Provincia, "CABA") ~ "Capital Federal",
    str_detect(Provincia, "Entre") ~ "Entre Ríos",
    str_detect(Provincia, "Santa") ~ "Santa Fé",
    str_detect(Provincia, "del") ~ "Santiago del Estero",
    TRUE ~ as.character(Provincia)
  )) 

base3_2020 <- base2_2020 %>%  
  mutate(Departamento = case_when(
    str_detect(Departamento, regex("Pampa", ignore_case = TRUE)) ~ "La Pampa",
    str_detect(Departamento, "Rioja") ~ "La Rioja",
    str_detect(Departamento, "Juan") ~ "San Juan",
    str_detect(Departamento, "Luis") ~ "San Luis",
    TRUE ~ as.character(Departamento)
  ))

write_excel_csv (base3_2020, "2020_nuevo.csv")
```

Intentando la unión entre las tablas

```{r}

casos_2020 <- read_csv ("2020_final.csv")
casos_2019 <- read_csv ("2019_final.csv",locale = locale(encoding = "ISO-8859-1"))
casos_2018 <- read_csv ("2018_final.csv")
casos_2017 <- read_csv ("2017_final.csv")
casos_2016 <- read_csv ("2016_final.csv", locale = locale(encoding = "ISO-8859-1"))

Prueba<-casos_2020 %>% 
  full_join(casos_2019) %>% 
  full_join(casos_2018) %>% 
  full_join(casos_2017) %>% 
  full_join(casos_2016)

Prueba %>%
  filter (Provincia== "Chaco") %>% 
  arrange (desc(Departamento)) 

Prueba <- Prueba %>% mutate(Departamento = case_when(
    str_detect(Departamento, regex("Zarate", ignore_case = TRUE)) ~ "Zárate",
    str_detect(Departamento, regex("Vicente Lop[e|é]z", ignore_case = TRUE)) ~ "Vicente López",
    str_detect(Departamento, regex("San Nicol[a|á]s", ignore_case = TRUE)) ~ "San Nicolás",
    str_detect(Departamento, regex("San Fernando", ignore_case = TRUE)) ~ "San Fernando",
    str_detect(Departamento, regex("Presidente Per[o|ó]n", ignore_case = TRUE)) ~ "Presidente Perón",
    str_detect(Departamento, regex("^Pil", ignore_case = TRUE)) ~ "Pilar",
    str_detect(Departamento, regex("Pehuaj[o|ó]", ignore_case = TRUE)) ~ "Pehuajó",
    str_detect(Departamento, regex("Necochea", ignore_case = TRUE)) ~ "Necochea",
    str_detect(Departamento, regex("Mor[o|ó]n", ignore_case = TRUE)) ~ "Morón",
    str_detect(Departamento, regex("Moreno", ignore_case = TRUE)) ~ "Moreno",
    str_detect(Departamento, regex("Merlo", ignore_case = TRUE)) ~ "Merlo",
    str_detect(Departamento, regex("Mercedes", ignore_case = TRUE)) ~ "Mercedes",
    str_detect(Departamento, regex("Marcos Paz", ignore_case = TRUE)) ~ "Marcos Paz",
    str_detect(Departamento, regex("Malvinas Argentinas", ignore_case = TRUE)) ~ "Malvinas Argentinas",
     str_detect(Departamento, regex("Luj[a|á]n", ignore_case = TRUE)) ~ "Luján",
    str_detect(Departamento, regex("^Lomas", ignore_case = TRUE)) ~ "Lomas de Zamora",
     str_detect(Departamento, regex("Lan[ú|u]s", ignore_case = TRUE)) ~ "Lanús",
    str_detect(Departamento, regex("Jun[i|í]n", ignore_case = TRUE)) ~ "Junín",
    str_detect(Departamento, regex("^Jos", ignore_case = TRUE)) ~ "José C. Paz",
    str_detect(Departamento, regex("Ituzaing[o|ó]", ignore_case = TRUE)) ~ "Ituzaingó",
   str_detect(Departamento, regex("General San Mart[i|í]n", ignore_case = TRUE)) ~ "General San Martín",
    str_detect(Departamento, regex("General Rodr[i|í]guez", ignore_case = TRUE)) ~ "General Rodríguez",
    str_detect(Departamento, regex("General Pueyrred[o|ó]n", ignore_case = TRUE)) ~ "General Pueyrredón",
    str_detect(Departamento, regex("Exaltaci[o|ó]n de la Cruz", ignore_case = TRUE)) ~ "Exaltación de la Cruz",
    str_detect(Departamento, regex("Esteban Echeverr[i|í]a", ignore_case = TRUE)) ~ "Esteban Echeverría",
    str_detect(Departamento, regex("Almirante Brown", ignore_case = TRUE)) ~ "Almirante Brown",
         TRUE ~ as.character(Departamento)
  ))

write_excel_csv (Prueba, "Matriz_completa.csv")

Prueba<-Prueba  %>% replace(is.na(.), 0)# remplazo los NA por 0 (ceros).

```

```{r}
Prueba <- read_csv ("Matriz_completa.csv")# a esta matriz la puli y es diferente a la anterior.

Prueba %>% group_by(Provincia, Departamento) %>% 
  mutate(suma= sum(Casos_2020))

Prueba %>% 
  filter (Provincia=="Santa Fé") %>% 
  arrange(desc(Departamento))

```

Datos de la población estimada en los diferentes departamentos de la Argentina. Datos provistos por el INDEC.

```{r}
library (readxl)
buenosAires <- read_excel ("./poblacion_estimada/proy_1025_depto_buenos_aires.xls")

buenos_aires <- buenosAires %>% 
  select ("Partido",`2016`: `2020`) %>% 
  slice (1:141) %>% 
  na.omit() %>% 
  mutate (Provincia= "Buenos Aires") %>% 
  relocate (Provincia, .before = Partido) %>% 
  slice (-1) %>% 
  rename (Departamento = Partido) 

caba <- read_excel ("./poblacion_estimada/proy_1025_depto_caba.xls")

caba <- caba %>% 
  select ("Comuna",`2016`: `2020`) %>% 
  slice (1:19) %>% 
  na.omit() %>% 
  mutate (Provincia= "Capital Federal") %>% 
  relocate (Provincia, .before = Comuna) %>% 
  slice (-1) %>% 
  mutate (Comuna= str_replace_all(Comuna, c("^1$" = "COMUNA 1",
                                            "2" = "COMUNA 2",
                                            "3" = "COMUNA 3",
                                            "4" = "COMUNA 4",
                                            "5" = "COMUNA 5",
                                            "6" = "COMUNA 6",
                                            "7" = "COMUNA 7",
                                            "8" = "COMUNA 8",
                                            "9" = "COMUNA 9",
                                            "10" = "COMUNA 10",
                                            "11" = "COMUNA 11"
                                            ))) %>% 
  rename (Departamento = Comuna) 

catamarca <- read_excel ("./poblacion_estimada/proy_1025_depto_catamarca.xls")

catamarca <- catamarca %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:20) %>% 
  na.omit(catamarca) %>% 
  mutate (Provincia= "Catamarca") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

chaco <- read_excel ("./poblacion_estimada/proy_1025_depto_chaco.xls")

chaco <- chaco %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:29) %>% 
  na.omit() %>% 
  mutate (Provincia= "Chaco") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

cordoba <- read_excel ("./poblacion_estimada/proy_1025_depto_cordoba.xls")

cordoba <- cordoba %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:30) %>% 
  na.omit() %>% 
  mutate (Provincia= "Córdoba") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

corrientes <- read_excel ("./poblacion_estimada/proy_1025_depto_corrientes.xls")

corrientes <- corrientes %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:29) %>% 
  na.omit() %>% 
  mutate (Provincia= "Corrientes") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

entre_rios <- read_excel ("./poblacion_estimada/proy_1025_depto_entre_rios.xls")

entre_rios <- entre_rios %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:21) %>% 
  na.omit() %>% 
  mutate (Provincia= "Entre Ríos") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

formosa <- read_excel ("./poblacion_estimada/proy_1025_depto_formosa.xls")

formosa <- formosa %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:13) %>% 
  na.omit() %>% 
  mutate (Provincia= "Formosa") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

jujuy <- read_excel ("./poblacion_estimada/proy_1025_depto_jujuy.xls")

jujuy <- jujuy %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:20) %>% 
  na.omit() %>% 
  mutate (Provincia= "Jujuy") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

la_pampa <- read_excel ("./poblacion_estimada/proy_1025_depto_la_pampa.xls")

la_pampa <- la_pampa %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:26) %>% 
  na.omit() %>% 
  mutate (Provincia= "La Pampa") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

la_rioja <- read_excel ("./poblacion_estimada/proy_1025_depto_la_rioja.xls")

la_rioja <- la_rioja %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:22) %>% 
  na.omit() %>% 
  mutate (Provincia= "La Rioja") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

mendoza <- read_excel ("./poblacion_estimada/proy_1025_depto_mendoza.xls")

mendoza <- mendoza %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:22) %>% 
  na.omit() %>% 
  mutate (Provincia= "Mendoza") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

misiones <- read_excel ("./poblacion_estimada/proy_1025_depto_misiones.xls")

misiones <- misiones %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:21) %>% 
  na.omit() %>% 
  mutate (Provincia= "Misiones") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

salta <- read_excel ("./poblacion_estimada/proy_1025_depto_salta.xls")

salta <- salta %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:27) %>% 
  na.omit() %>% 
  mutate (Provincia= "Salta") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

san_juan <- read_excel ("./poblacion_estimada/proy_1025_depto_san_juan.xls")

san_juan <- san_juan %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:23) %>% 
  na.omit() %>% 
  mutate (Provincia= "San Juan") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

san_luis <- read_excel ("./poblacion_estimada/proy_1025_depto_san_luis.xls")

san_luis <- san_luis %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:14) %>% 
  na.omit() %>% 
  mutate (Provincia= "San Luis") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

santa_fe <- read_excel ("./poblacion_estimada/proy_1025_depto_santa_fe.xls")

santa_fe <- santa_fe %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:23) %>% 
  na.omit() %>% 
  mutate (Provincia= "Santa Fé") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

santiago_del_estero <- read_excel ("./poblacion_estimada/proy_1025_depto_santiago_del_estero.xls")

santiago_del_estero <- santiago_del_estero %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:32) %>% 
  na.omit() %>% 
  mutate (Provincia= "Santiago del Estero") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

tucuman <- read_excel ("./poblacion_estimada/proy_1025_depto_tucuman.xls")

tucuman <- tucuman %>% 
  select ("Departamento",`2016`: `2020`) %>% 
  slice (1:21) %>% 
  na.omit() %>% 
  mutate (Provincia= "Tucumán") %>% 
  relocate (Provincia, .before = Departamento) %>% 
  slice (-1)

```

Uniendo todos los data frames de la estimación poblacional (2016-2020) de los departamentos de las Provincias Argentinas con registro confirmado de casos de dengue.

```{r}

poblacion_total <-bind_rows(list(buenos_aires, caba, catamarca, chaco, cordoba, corrientes, entre_rios, formosa, jujuy, la_pampa, la_rioja, mendoza, misiones, salta, san_juan, san_luis, santa_fe, santiago_del_estero, tucuman)) 

poblacion_total <-poblacion_total %>% 
  unite(Provincia_Departamento, c("Provincia", "Departamento"))

casos_dengue <- read_csv("Matriz_completa.csv")

casos_dengue <-casos_dengue %>% 
  unite(Provincia_Departamento, c("Provincia", "Departamento"))

population_dengueCases <- left_join(casos_dengue, poblacion_total, by="Provincia_Departamento") %>% 
  separate(Provincia_Departamento, c("Provincia", "Departamento"), sep= "_") %>% 
  rename ("Population_2016" = "2016",
          "Population_2017" = "2017",
          "Population_2018" = "2018",
          "Population_2019" = "2019",
          "Population_2020" = "2020")

write_excel_csv(population_dengueCases, "population_dengueCases.csv")

```


